In [1]:
import numpy as np
from scipy.io import loadmat

A data file is available that contains a rank-2, 16-by-16 matrix Xtrue with integer entries and three versions of this matrix (Y1, Y2, and Y3) with differing numbers of missing entries. The missing entries are indicated by NaN.
A script is provided to complete a matrix using iterative singular value thresholding. The script contains a function that requires two inputs: 
    i) the matrix with missing entries, and 
    ii) the rank.

a) Apply the iterative singular value thresholding function (provided in the script) to the three incomplete matrices assuming the rank is 2. You will first need to complete the line of code in the function. Compare your recovered completed ma- trices to Xtrue (Note: compare the output by subtracting the completed matrix from the original matrix, and then displaying them). Does the number of missing entries affect the accuracy of the completed matrix?

b) Now apply your routine to the three incomplete matrices assuming the rank is 3. Compare your recovered completed matrices to Xtrue. Comment on the impact of using the incorrect rank in the completion process.

In [2]:
Xtrue = loadmat("incomplete.mat")["Xtrue"]
Y1 = loadmat("incomplete.mat")["Y1"]
Y2 = loadmat("incomplete.mat")["Y2"]
Y3 = loadmat("incomplete.mat")["Y3"]
Xtrue

array([[30, 12, 24,  8, 12, 14, 12, 12, 22, 24, 14, 10, 14, 24, 20, 12],
       [30, 21, 15, 11, 21, 26, 12, 21, 10, 15, 17, 16,  8, 15, 23, 12],
       [15,  9,  9,  5,  9, 11,  6,  9,  7,  9,  8,  7,  5,  9, 11,  6],
       [35, 16, 26, 10, 16, 19, 14, 16, 23, 26, 17, 13, 15, 26, 24, 14],
       [15,  9,  9,  5,  9, 11,  6,  9,  7,  9,  8,  7,  5,  9, 11,  6],
       [25, 11, 19,  7, 11, 13, 10, 11, 17, 19, 12,  9, 11, 19, 17, 10],
       [45, 24, 30, 14, 24, 29, 18, 24, 25, 30, 23, 19, 17, 30, 32, 18],
       [30, 15, 21,  9, 15, 18, 12, 15, 18, 21, 15, 12, 12, 21, 21, 12],
       [25, 11, 19,  7, 11, 13, 10, 11, 17, 19, 12,  9, 11, 19, 17, 10],
       [20, 13, 11,  7, 13, 16,  8, 13,  8, 11, 11, 10,  6, 11, 15,  8],
       [45, 24, 30, 14, 24, 29, 18, 24, 25, 30, 23, 19, 17, 30, 32, 18],
       [30, 15, 21,  9, 15, 18, 12, 15, 18, 21, 15, 12, 12, 21, 21, 12],
       [25, 17, 13,  9, 17, 21, 10, 17,  9, 13, 14, 13,  7, 13, 19, 10],
       [40, 20, 28, 12, 20, 24, 16, 20, 24, 28, 20,

In [3]:
def ItSingValThresh(Y, r):
    """
    Iterative Singular Value Thresholding function for Matrix Completion
    """
    tol = 10**(-3)  # difference between iterates at termination
    max_its = 100
    n,p = Y.shape 
    X = np.array(Y) #make a copy so operations do not mutate the original
    X[np.isnan(X)] = 0 # Fill in missing entries with zeros

    err = 10**6 
    itt = 0
    
    while err > tol and itt < max_its:
        U,s,VT = np.linalg.svd(X, full_matrices=False)
        V, S = VT.T, np.diag(s)
        Xnew = U[:,0:r]@S[:r,:r]@VT[0:r,] ### Complete this line
        for i in range(n):
            for j in range(p):
                if ~np.isnan(Y[i,j]):  #replace Xnew with known entries
                    Xnew[i,j] = Y[i,j]
        err = np.linalg.norm(X-Xnew,'fro') 
        X = Xnew
        itt += 1
    return X

In [5]:
X_Y1_1 = ItSingValThresh(Y1,2)
X_Y1_1

array([[-10.74349156,  10.68645274,  24.        ,   8.        ,
         12.        ,  14.        ,  11.71652349,  21.6722056 ,
         22.        ,  24.45722177,  14.00425824,  10.        ,
         14.        ,  24.        ,  19.70903394,  12.1365816 ],
       [ 57.84397298,  21.        ,  16.97657529,  10.43358065,
         20.0803537 ,  24.50168206,  12.36334769,  -4.73331304,
         12.48733069,  15.        ,  17.        ,  15.18748793,
          8.        ,  15.        ,  23.        ,  12.22178391],
       [ 17.09524075,   8.45115897,   9.66940489,   4.75386984,
          9.        ,  10.33971979,   6.04348723,   2.14697858,
          7.78742466,   9.        ,   8.        ,   6.62932556,
          5.        ,   9.13101055,  10.82857606,   6.        ],
       [  4.67681341,  14.89879653,  26.40953881,  10.        ,
         16.11527203,  18.65645327,  13.86007656,  18.70048713,
         23.        ,  26.16977666,  17.        ,  12.74936693,
         15.49100979,  26.        ,  

In [6]:
(X_Y1_1-Xtrue).round(2)

array([[-4.074e+01, -1.310e+00,  0.000e+00,  0.000e+00,  0.000e+00,
         0.000e+00, -2.800e-01,  9.670e+00,  0.000e+00,  4.600e-01,
         0.000e+00,  0.000e+00,  0.000e+00,  0.000e+00, -2.900e-01,
         1.400e-01],
       [ 2.784e+01,  0.000e+00,  1.980e+00, -5.700e-01, -9.200e-01,
        -1.500e+00,  3.600e-01, -2.573e+01,  2.490e+00,  0.000e+00,
         0.000e+00, -8.100e-01,  0.000e+00,  0.000e+00,  0.000e+00,
         2.200e-01],
       [ 2.100e+00, -5.500e-01,  6.700e-01, -2.500e-01,  0.000e+00,
        -6.600e-01,  4.000e-02, -6.850e+00,  7.900e-01,  0.000e+00,
         0.000e+00, -3.700e-01,  0.000e+00,  1.300e-01, -1.700e-01,
         0.000e+00],
       [-3.032e+01, -1.100e+00,  4.100e-01,  0.000e+00,  1.200e-01,
        -3.400e-01, -1.400e-01,  2.700e+00,  0.000e+00,  1.700e-01,
         0.000e+00, -2.500e-01,  4.900e-01,  0.000e+00,  0.000e+00,
         2.100e-01],
       [ 3.500e+00,  0.000e+00,  0.000e+00, -1.900e-01, -2.100e-01,
        -4.400e-01,  6.000e-02, 

In [7]:
X_Y2_1 = ItSingValThresh(Y2,2)
X_Y2_1

array([[30.        , 11.99939894, 24.        ,  8.        , 12.        ,
        14.        , 12.        , 11.99936431, 22.        , 24.00062999,
        13.99984645, 10.        , 14.        , 24.        , 20.        ,
        11.99990474],
       [30.        , 21.        , 15.00102259, 11.        , 21.        ,
        25.99768463, 12.        , 21.        , 10.00235779, 15.        ,
        17.        , 15.99944582,  8.        , 15.        , 23.        ,
        12.00014129],
       [14.99984328,  9.        ,  8.99994406,  4.99999441,  9.        ,
        10.99958042,  5.99994293,  9.0001144 ,  7.        ,  9.        ,
         8.        ,  7.        ,  5.        ,  8.99973475, 11.        ,
         6.        ],
       [35.        , 15.99962561, 26.00014012, 10.        , 15.99980617,
        19.00004465, 14.00000176, 15.99964215, 23.        , 26.00044282,
        17.        , 13.        , 15.        , 26.        , 24.        ,
        13.9999523 ],
       [14.99987949,  9.        ,  9

In [8]:
print((X_Y2_1-Xtrue).round(2))

[[ 0. -0.  0.  0.  0.  0.  0. -0.  0.  0. -0.  0.  0.  0.  0. -0.]
 [ 0.  0.  0.  0.  0. -0.  0.  0.  0.  0.  0. -0.  0.  0.  0.  0.]
 [-0.  0. -0. -0.  0. -0. -0.  0.  0.  0.  0.  0.  0. -0.  0.  0.]
 [ 0. -0.  0.  0. -0.  0.  0. -0.  0.  0.  0.  0.  0.  0.  0. -0.]
 [-0.  0.  0.  0. -0. -0. -0. -0.  0.  0.  0. -0.  0.  0.  0. -0.]
 [ 0.  0.  0.  0. -0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-0. -0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -0. -0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -0.  0.  0.]
 [-0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -0.  0.  0.  0.]
 [ 0. -0.  0.  0.  0. -0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -0.  0.  0.  0.  0.  0.  0.  0. -0.  0.  0.]
 [-0.  0.  0.  0.  0.  0.  0.  0.  0. -0.  0.  0.  0. -0.  0. 

In [9]:
X_Y3_1 = ItSingValThresh(Y3,2)
X_Y3_1

array([[30.        , 12.        , 24.        ,  8.        , 12.        ,
        14.        , 12.        , 12.        , 22.        , 24.        ,
        14.00002067, 10.        , 14.        , 24.        , 20.        ,
        12.        ],
       [30.        , 21.        , 15.        , 11.        , 21.        ,
        26.        , 12.        , 21.        , 10.        , 15.        ,
        17.        , 15.99989032,  8.        , 15.        , 23.        ,
        12.        ],
       [14.9999749 ,  9.        ,  9.        ,  5.        ,  9.        ,
        11.        ,  6.        ,  9.        ,  7.        ,  9.        ,
         8.        ,  7.        ,  5.        ,  9.        , 11.        ,
         6.        ],
       [35.        , 16.        , 25.99990584, 10.        , 16.        ,
        19.        , 13.99998225, 16.        , 23.        , 26.        ,
        17.        , 13.        , 15.        , 26.        , 24.        ,
        14.        ],
       [15.        ,  9.        ,  9

In [10]:
print((X_Y3_1-Xtrue).round(2))

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -0.  0.  0.  0.  0.]
 [-0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -0.  0.  0.  0. -0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -0.  0.  0.  0.  0. -0. -0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 

In [11]:
Xtrue_2 = loadmat("incomplete.mat")["Xtrue"]
Y1_2 = loadmat("incomplete.mat")["Y1"]
Y2_2 = loadmat("incomplete.mat")["Y2"]
Y3_2 = loadmat("incomplete.mat")["Y3"]

In [12]:
X_Y1_2 = ItSingValThresh(Y1_2,3)
X_Y1_2

array([[-19.98141818,   8.97068141,  24.        ,   8.        ,
         12.        ,  14.        ,  11.26293208,  21.89911472,
         22.        ,  24.95361171,  14.48958395,  10.        ,
         14.        ,  24.        ,  19.69190377,  12.49013054],
       [ 43.67459233,  21.        ,  14.93020401,  10.14377823,
         18.04369409,  15.5243743 ,  12.59686948,  -2.79931792,
         14.83277584,  15.        ,  17.        ,  14.08917011,
          8.        ,  15.        ,  23.        ,  12.21745701],
       [ 12.99048682,   5.92994154,  13.02542214,   4.74029113,
          9.        ,  15.00876119,   5.85664366,   1.23235008,
          8.11149626,   9.        ,   8.        ,   6.17790085,
          5.        ,   7.30808421,  10.53959933,   6.        ],
       [ -0.93515236,  17.49117063,  19.64485262,  10.        ,
         16.87450108,   9.09953777,  13.70070092,  17.49150829,
         23.        ,  24.40707471,  17.        ,  13.02258673,
         15.31393156,  26.        ,  

In [13]:
(X_Y1_2-Xtrue).round(2)

array([[-4.998e+01, -3.030e+00,  0.000e+00,  0.000e+00,  0.000e+00,
         0.000e+00, -7.400e-01,  9.900e+00,  0.000e+00,  9.500e-01,
         4.900e-01,  0.000e+00,  0.000e+00,  0.000e+00, -3.100e-01,
         4.900e-01],
       [ 1.367e+01,  0.000e+00, -7.000e-02, -8.600e-01, -2.960e+00,
        -1.048e+01,  6.000e-01, -2.380e+01,  4.830e+00,  0.000e+00,
         0.000e+00, -1.910e+00,  0.000e+00,  0.000e+00,  0.000e+00,
         2.200e-01],
       [-2.010e+00, -3.070e+00,  4.030e+00, -2.600e-01,  0.000e+00,
         4.010e+00, -1.400e-01, -7.770e+00,  1.110e+00,  0.000e+00,
         0.000e+00, -8.200e-01,  0.000e+00, -1.690e+00, -4.600e-01,
         0.000e+00],
       [-3.594e+01,  1.490e+00, -6.360e+00,  0.000e+00,  8.700e-01,
        -9.900e+00, -3.000e-01,  1.490e+00,  0.000e+00, -1.590e+00,
         0.000e+00,  2.000e-02,  3.100e-01,  0.000e+00,  0.000e+00,
         5.200e-01],
       [-3.000e+00,  0.000e+00,  0.000e+00, -2.400e-01, -6.700e-01,
        -3.530e+00,  1.900e-01, 

In [14]:
X_Y2_2 = ItSingValThresh(Y2,3)
X_Y2_2

array([[30.        , 11.99933387, 24.        ,  8.        , 12.        ,
        14.        , 12.        , 11.99877943, 22.        , 24.00048162,
        14.00004427, 10.        , 14.        , 24.        , 20.        ,
        11.99986489],
       [30.        , 21.        , 15.00072263, 11.        , 21.        ,
        25.99720943, 12.        , 21.        , 10.00206008, 15.        ,
        17.        , 15.99935527,  8.        , 15.        , 23.        ,
        12.0000628 ],
       [ 4.99492044,  9.        ,  8.99997972,  5.00000202,  9.        ,
        10.99970007,  5.99998748,  9.00049428,  7.        ,  9.        ,
         8.        ,  7.        ,  5.        ,  8.99986059, 11.        ,
         6.        ],
       [35.        , 15.99903119, 26.00014604, 10.        , 15.99928282,
        18.99920208, 13.99980943, 15.99862585, 23.        , 26.00037504,
        17.        , 13.        , 15.        , 26.        , 24.        ,
        13.99975507],
       [ 6.11533377,  9.        ,  9

In [15]:
print((X_Y2_2-Xtrue).round(2))

[[  0.    -0.     0.     0.     0.     0.     0.    -0.     0.     0.
    0.     0.     0.     0.     0.    -0.  ]
 [  0.     0.     0.     0.     0.    -0.     0.     0.     0.     0.
    0.    -0.     0.     0.     0.     0.  ]
 [-10.01   0.    -0.     0.     0.    -0.    -0.     0.     0.     0.
    0.     0.     0.    -0.     0.     0.  ]
 [  0.    -0.     0.     0.    -0.    -0.    -0.    -0.     0.     0.
    0.     0.     0.     0.     0.    -0.  ]
 [ -8.88   0.     0.     0.    -0.    -0.    -0.     0.     0.     0.
    0.    -0.     0.     0.     0.    -0.  ]
 [-14.24   0.     0.     0.    -0.     0.     0.     0.     0.     0.
    0.     0.     0.     0.     0.    -0.  ]
 [  0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
    0.     0.     0.     0.     0.     0.  ]
 [-21.71  -0.     0.    -0.     0.     0.     0.     0.     0.     0.
    0.     0.     0.     0.     0.     0.  ]
 [  0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
    0.    

In [16]:
X_Y3_2 = ItSingValThresh(Y3,3)
X_Y3_2

array([[30.        , 12.        , 24.        ,  8.        , 12.        ,
        14.        , 12.        , 12.        , 22.        , 24.        ,
        13.99997171, 10.        , 14.        , 24.        , 20.        ,
        12.        ],
       [30.        , 21.        , 15.        , 11.        , 21.        ,
        26.        , 12.        , 21.        , 10.        , 15.        ,
        17.        , 15.9997824 ,  8.        , 15.        , 23.        ,
        12.        ],
       [ 5.7558657 ,  9.        ,  9.        ,  5.        ,  9.        ,
        11.        ,  6.        ,  9.        ,  7.        ,  9.        ,
         8.        ,  7.        ,  5.        ,  9.        , 11.        ,
         6.        ],
       [35.        , 16.        , 26.00004657, 10.        , 16.        ,
        19.        , 14.00000833, 16.        , 23.        , 26.        ,
        17.        , 13.        , 15.        , 26.        , 24.        ,
        14.        ],
       [15.        ,  9.        ,  9

In [19]:
print((X_Y3_2-Xtrue).round(2))

[[  0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
   -0.     0.     0.     0.     0.     0.  ]
 [  0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
    0.    -0.     0.     0.     0.     0.  ]
 [ -9.24   0.     0.     0.     0.     0.     0.     0.     0.     0.
    0.     0.     0.     0.     0.     0.  ]
 [  0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
    0.     0.     0.     0.     0.     0.  ]
 [  0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
    0.    -0.     0.     0.     0.     0.  ]
 [-13.52   0.     0.     0.     0.     0.     0.     0.     0.     0.
    0.     0.     0.     0.     0.     0.  ]
 [  0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
    0.     0.     0.     0.     0.     0.  ]
 [  0.    -0.     0.     0.     0.     0.     0.     0.     0.     0.
    0.     0.     0.     0.     0.     0.  ]
 [  0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
    0.    

In [20]:
print("Y1, rank 2 error: ", np.linalg.norm(Xtrue - X_Y1_1, 'fro'))
print("Y2, rank 2 error: ", np.linalg.norm(Xtrue - X_Y2_1, 'fro'))
print("Y3, rank 2 error: ", np.linalg.norm(Xtrue - X_Y3_1, 'fro'))

print("Y1, rank 3 error: ", np.linalg.norm(Xtrue - X_Y1_2, 'fro'))
print("Y2, rank 3 error: ", np.linalg.norm(Xtrue - X_Y2_2, 'fro'))
print("Y3, rank 3 error: ", np.linalg.norm(Xtrue - X_Y3_2, 'fro'))

Y1, rank 2 error:  87.24667705099662
Y2, rank 2 error:  0.004735599527383206
Y3, rank 2 error:  0.0007153218655222742
Y1, rank 3 error:  128.778048467721
Y2, rank 3 error:  48.97940976510776
Y3, rank 3 error:  20.785069891601808
